### ISSUE TITLE
Toasts with action `freeze` when you hit fast on the action buttons

### ISSUE THREAD

**Issue by sadeghbarati** [xiaoluoboding/vue-sonner#39]
In addition to freezing, toast with close actions will removed instantly without animation

https://github.com/radix-vue/shadcn-vue/assets/17789047/71133b00-edd1-4359-b75a-bd5025482083

**Comment by xiaoluoboding** [comment]
I found that this bug is caused by a hierarchical issue, which results in the action button being unclickable.

fixed on the new release v1.0.3

**Comment by sadeghbarati** [comment]
@xiaoluoboding 

I think we still have issues with custom class names

I didn't notice this 👇 

- React Sonner --->  [`classNames`](https://github.com/emilkowalski/sonner/blob/main/src/types.ts#L62) ---> `ToastClassnames` interface
- Vue Sonner ---> [`className`](https://github.com/xiaoluoboding/vue-sonner/blob/main/packages/types.ts#L45) ---> `string`


![image](https://github.com/xiaoluoboding/vue-sonner/assets/17789047/819c966d-292c-4128-adda-3704f2ae145f)
